config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :posts do
    resources :comments
  end

  root "posts#index"
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 140 }
  validates :content, presence: true
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #mount avatar uploader
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  #configure permitted parameters for devise
  def configure_permitted_parameters
    added_attrs = [:email, :password, :password_confirmation, :remember_me, :avatar, :avatar, :avatar_cache]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :comment))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  def edit
    @post = post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_params, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Created successfully!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error creating post"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Updated successfully"
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  #def about
  #end

  private
    def post_params
      params.require(:post).permit(:title,:content)
    end

    def find_params
      @post = Post.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.name %>:</strong>
          <%= raw(comment.comment) %>
        </p>
      </div>
    </div>
    <div class="options" style="margin: 5px;">
      <%= link_to 'Delete', [comment.post, comment],
                   method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %> |
      <%= link_to 'Edit', '#' %>
    </div>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
<!--
collection.build(attributes = {}, …) Returns one or more new objects of the collection type
that have been instantiated with attributes and linked to this object through a foreign key,
but have not yet been saved. Note: This only works if an associated object already exists, not if it‘s nil!
-->
  <div class="form-group">
      <%= f.input :name, class: "form-control" %>
  </div>

  <div class="form-group">
      <%= f.input :comment, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit, 'Leave a reply', class: "button is-primary" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h6>Edit Comment</h6>
<%= render 'comments/form' %>

app/views/layouts/_navigation.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
    nav {
      position: relative;
      border: 2px solid black;
      height: 40px;
      background-color: #dcf8d3;
    }
    li {
      float: left;
      padding-right: 40px;
      list-style: none;
      position: relative;
      bottom: 4px;
    }
  </style>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <% if user_signed_in? %>
        <!--This block is only visible to signed in admins -->
          <li><%= link_to 'New Post', new_post_path %></li>
          <li><%= link_to 'My Account', edit_user_registration_path  %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
        <!-- The block ends here -->
        <% else %>
          <li><%= link_to 'Login', new_user_session_path  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
</body>
<html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SauraBlog</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "layouts/navigation" %>

    <div class="main-body-left" id="main-div-body">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>



<!--My footer // -->
    <div class="container">
        <div class="text-center center-block">
            <p class="txt-railway">sauramandal.wordpress.com</p>
              <br />
                <a href="https://www.facebook.com/saura.mandal"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
    	           <a href="https://twitter.com/bootsnipp"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
    	           <a href="https://plus.google.com/u/0/105149871306601499119"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
    	           <a href="sauram@mindfiresolutions.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
        </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<!-- My custom form
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="posts/_form_style.css" type="text/css">
</head>
<body>
<div class="form-section">
  <%= simple_form_for @post do |f| %>
    <div class="field">
      <div class="control">
        <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label'} %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :content, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "input" %>
      </div>
    </div>
    <%= f.button :submit, 'Create post', class: "button-is-primary" %>
  <% end %>
</div>
</body>
</html>
-->

<!-- Bootstrap form -->
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :content, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
  
<% end %>

app/views/posts/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="posts/_form_style.css" type="text/css">
</head>
  <body>
    <% content_for :page_title, "Edit Post" %>
    <div class="form-section">
      <%= simple_form_for @post do |f| %>
        <div class="field">
          <div class="control">
            <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label'} %>
          </div>
        </div>

        <div class="field">
          <div class="control">
            <%= f.input :content, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "input" %>
          </div>
        </div>
        <%= f.button :submit, 'Update post', class: "button-is-primary" %>
      <% end %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Nunito:800" rel="stylesheet">
  <link rel="stylesheet" href="posts/index_style.css" type="text/css">
</head>
<body>
  <h1 class="text-left" style="font-size: 60px; font-family: 'Nunito', sans-serif;">My Blog</h1>
  <div class="new-post">
    <h4 class="new-post-button"><%= link_to "Create a new post", new_post_path %></h4>
  </div>

  <div class="section-container">
    <div class="container">
      <% @posts.each do |post| %>
        <div class="post-container">
          <div class="post-title">
            <p>
              <h3>Title: <%= post.title %></h3>
              <%= link_to 'view post', post %>
            </p>
          </div>
          <div class="created_at">
            <h6><%= post.created_at.strftime('%b %d, %Y') %></h6>
          </div>
          <div class="post-content">
            <h3 class="content-div">Content: </h3><%= raw(post.content).truncate(358) %>
          </div>
          <div class="read-more">
            <%= link_to "READ MORE", post_path(post) %>
          </div>
          <div class="post-comments-count">
            <span class="tag-rounded"><%= post.comments.count %> comments </span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/posts/new.html.erb
<% content_for :page_title, "Create a new post" %>
<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :page_title, @post.title %>

<section class="section">
  <div class="container">
    <nav class="level">
      <!-- Left Side -->
      <div class="level-container" style="padding-top: 5px;">
          <strong style="padding: 5px;">Actions: </strong>
          <%= link_to "Edit", edit_post_path(@post), class: "button" %> |
          <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "button-is-danger" %>
      </div>
    </nav>
    <br>
    <div class="content">
      <h3>Post: </h3>
      <%= raw(@post.content) %>
    </div>
  </div>
</section>

<section class="section comments">
  <div class="container">
    <h2 class="subtitle is-5"> <strong><%= @post.comments.count %></strong> Comments </h2>
    <%= render @post.comments %>
    <div class="comment-form">
      <hr/>
      <h3 class="subtitle is-3">Leave a reply</h3>
      <%= render 'comments/form' %>
    </div>
  </div>
</section>

<!-- <section class="back-button">
  <hr/>
  <div class="button">
    <%= link_to "Back to home", posts_path %>
  </div>
</section> -->

app/views/users/shared/_links.html.erb
<div class="col-sm-offset-4 col-sm-4 col-xs-12">
  <% if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.omniauthable? %>
    <% resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
  <% end %>
</div>